name: NPM Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: yarn
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v4
        with:
          package: ./dist/package.json
